#! /usr/local/std/bin/ksh -f

lib=xsunlib

nawk ' 

/^.model/ { file = $2
	    print $0 > file
	    inmod = 1
	    next
	    } 
	    
	  { if (inmod == 1) {
		print $0 > file
		if( $1 != "+" ) {
		   inmod = 0
		   close( file )
		   }
	    }
	   }

/^.subckt/ { file = $2
	     print $0 > file
	     insub = 1
	     next
	     }

	   { if (insub == 1) {
		print $0 > file
		if( $1 == ".ends" ) {
		   insub = 0
		   close( file )
		   }
	     }
	   }

	  ' < $lib
