#! /bin/sh

if [ -s $1.sp ] ; then
   h9002 $1.sp > $1.spout
fi

nawk '
	BEGIN {print "*** CAzM simulation ***"
	       print ""
	       print "TRANSFER ANALYSIS"
	       print "Volt Qgs Qgd"}

/^       volt/,/^$/ { if($1!="volt" && $1!="" && NF==3 ) {
			printf("%11.5e  %11.5e  %11.5e\n",$1,$2,$3) 
			} 
		     }' < $1.spout > $1.spsig

