package busticketbookingsystem;

import java.net.*;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.DefaultListModel;

public class CustEnqiry extends javax.swing.JInternalFrame
{
    /** Creates new form CustEnqiry */
    public CustEnqiry() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3SelRoute = new javax.swing.JLabel();
        jLabel4AlailInfo = new javax.swing.JLabel();
        Lsource = new javax.swing.JLabel();
        Ldestn = new javax.swing.JLabel();
        SelectRouteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailabilityListBox = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tbusid = new javax.swing.JTextField();
        BookTicketButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        sourceTxt = new javax.swing.JTextField();
        destnTxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Rs_ID_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Customer Enquiry"); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3SelRoute.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3SelRoute.setText("Select Route"); // NOI18N
        getContentPane().add(jLabel3SelRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 83, 23));

        jLabel4AlailInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4AlailInfo.setText("Availability Information"); // NOI18N
        getContentPane().add(jLabel4AlailInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        Lsource.setText("Source"); // NOI18N
        getContentPane().add(Lsource, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        Ldestn.setText("Destination"); // NOI18N
        getContentPane().add(Ldestn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        SelectRouteButton.setText("Ok"); // NOI18N
        SelectRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRouteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SelectRouteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 10, 210));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 620, 10));

        jScrollPane1.setViewportView(AvailabilityListBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 290, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Customer Information"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, -1));

        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });
        getContentPane().add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 240, -1));

        jLabel4.setText("Name"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 40, 20));

        jLabel5.setText("Age"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 30, 20));
        getContentPane().add(Tage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, -1));

        jLabel6.setText("Date"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 30, -1));

        jLabel8.setText(" Bus Id"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 40, 20));
        getContentPane().add(Tbusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 80, 20));

        BookTicketButton.setText("Book Ticket"); // NOI18N
        BookTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicketButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BookTicketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 200, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 630, 10));

        jLabel11.setText("Date"); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, -1));
        getContentPane().add(sourceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));
        getContentPane().add(destnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", " " }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 60, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", " " }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 60, -1));

        jLabel2.setText("Reservation_ID :"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));
        getContentPane().add(Rs_ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Bus_ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tictek Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 70, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Seats Booked");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 30, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    javax.swing.DefaultListModel LM = new javax.swing.DefaultListModel();
    int MaxSeatNo=0;
    private void SelectRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRouteButtonActionPerformed

        Connection con;
	Statement s1;
        ResultSet records;

        int returnVal;
        String BusId;
        int MaxSeatNo=0;
        int TotalSeats=0;
        int i=0;
        String s="";        
        String rs_id="";


	try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
           // Class.forName("org.apache.derby.jdbc.ClientDriver");
            con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:SCT","hirak","hirak123");
           //con = DriverManager.getConnection("jdbc:derby://localhost:1527/BusSystem", "ishan", "ishan");

            s1 = con.createStatement();
            s="select X.bus_id,total_seats,Maximum from (select bus_id,total_seats from bus,route where bus.route=route.route_id and source='" + sourceTxt.getText() + "' and destination='" + destnTxt.getText() + "') X left outer join (select  bus,max(seat_no)as Maximum from reservation where booking_dt='" + jComboBox4.getSelectedItem()+ "-"+ jComboBox5.getSelectedItem()+"-"+jComboBox6.getSelectedItem() + "'group by bus)y on X.bus_id = y.bus";
            System.out.println(s);
            records=s1.executeQuery(s);
            
            while (records.next())
            {
            BusId=records.getString(1);
            TotalSeats=records.getInt(2);
            MaxSeatNo=records.getInt(3);
            
            s="         ";
            s= BusId + "                    " + Integer.toString(TotalSeats) + "                        " + Integer.toString(MaxSeatNo);

            AvailabilityListBox.setModel(LM);
            LM.add(i, s);
            i++;
           }
        }

         catch(ClassNotFoundException e){
			System.out.println(e);
		}
		catch(SQLException e){
			System.out.println(e);
		}
		catch(Exception e){
			System.out.println(e);
		}

    }//GEN-LAST:event_SelectRouteButtonActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed

    private void BookTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicketButtonActionPerformed

        Connection con;
	Statement s1;
        int returnVal;
        
        int TotalSeats=0;
        String s="";
        ResultSet records;
        String rs_id="";


	try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            //Class.forName("org.apache.derby.jdbc.ClientDriver");

            con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:SCT","hirak","hirak123");
            //con = DriverManager.getConnection("jdbc:derby://localhost:1527/BusSystem", "ishan", "ishan");

            s1 = con.createStatement();
             System.out.print("abc");
             s="select max(seat_no)as Maximum from reservation where booking_dt='" + jComboBox4.getSelectedItem()+ "-"+ jComboBox5.getSelectedItem()+"-"+jComboBox6.getSelectedItem() + "' and bus='" + Tbusid.getText() + "' group by bus";
           System.out.print(s);
             records=s1.executeQuery(s);
               System.out.print("abc");
           while (records.next())
           {
            MaxSeatNo=records.getInt("Maximum");
           }

              System.out.print(MaxSeatNo);

              records=s1.executeQuery("select total_seats from bus where bus_id='"+ Tbusid.getText()+"'");
             
              while(records.next())
              {
              TotalSeats=records.getInt("total_seats");
            }

              if(MaxSeatNo == TotalSeats)
              {
                   System.out.print("All Seats are filled");
                   JOptionPane.showMessageDialog(null,"All Seats are filled");
              }
              else
              {

                  MaxSeatNo=MaxSeatNo+1;System.out.print(MaxSeatNo);
                  returnVal=s1.executeUpdate("insert into reservation values('"+Rs_ID_TextField.getText()+"','" + Tbusid.getText() + "',"+MaxSeatNo + ",'" + Tname.getText() + "',"+ Tage.getText() +",to_date('" + jComboBox1.getSelectedItem()+ "-"+ jComboBox2.getSelectedItem()+"-"+jComboBox3.getSelectedItem()+ "','DD-MON-YY'))");
              }

              records.close();
              con.close();
        }
        catch(ClassNotFoundException e){
			System.out.println(e);
		}
		catch(SQLException e){
			System.out.println(e);
		}
		catch(Exception e){
			System.out.println(e);
		}

    }//GEN-LAST:event_BookTicketButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AvailabilityListBox;
    private javax.swing.JButton BookTicketButton;
    private javax.swing.JLabel Ldestn;
    private javax.swing.JLabel Lsource;
    private javax.swing.JTextField Rs_ID_TextField;
    private javax.swing.JButton SelectRouteButton;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tbusid;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField destnTxt;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3SelRoute;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4AlailInfo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField sourceTxt;
    // End of variables declaration//GEN-END:variables

}
