/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainjFrameForm.java
 *
 * Created on Aug 12, 2010, 5:43:10 PM
 */

package busticketbookingsystem;

/**
 *
 * @author Ishan Mukherjee
 */
public class MainjFrameForm extends javax.swing.JFrame {

    /** Creates new form MainjFrameForm */
    public MainjFrameForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MbusEntry = new javax.swing.JMenuItem();
        MrouteEntry = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        McustEnquiry = new javax.swing.JMenuItem();
        ViewBus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Ticket Booking System");

        jMenu1.setText("New");

        MbusEntry.setText("New Bus");
        MbusEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbusEntryActionPerformed(evt);
            }
        });
        jMenu1.add(MbusEntry);

        MrouteEntry.setText("New Route");
        MrouteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrouteEntryActionPerformed(evt);
            }
        });
        jMenu1.add(MrouteEntry);

        jMainMenuBar.add(jMenu1);

        jMenu2.setText("Enquiry");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        McustEnquiry.setText("Cust Enquiry");
        McustEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McustEnquiryActionPerformed(evt);
            }
        });
        jMenu2.add(McustEnquiry);

        ViewBus.setText("View Bus");
        ViewBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBusActionPerformed(evt);
            }
        });
        jMenu2.add(ViewBus);

        jMainMenuBar.add(jMenu2);

        setJMenuBar(jMainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void McustEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McustEnquiryActionPerformed

        CustEnqiry F1 = new CustEnqiry();
        desktop.add(F1);
        F1.show();
    }//GEN-LAST:event_McustEnquiryActionPerformed

    private void MrouteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrouteEntryActionPerformed
        // TODO add your handling code here:
        NewRouteJInternalFrame F1 = new NewRouteJInternalFrame();
        desktop.add(F1);
        F1.show();
    }//GEN-LAST:event_MrouteEntryActionPerformed

    private void MbusEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbusEntryActionPerformed
        // TODO add your handling code here:
        NewBusJInternalFrame F1 = new NewBusJInternalFrame();
        desktop.add(F1);
        F1.show();

    }//GEN-LAST:event_MbusEntryActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void ViewBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBusActionPerformed
        // TODO add your handling code here:
        ViewBus F1 = new ViewBus();
        desktop.add(F1);
        F1.show();
    }//GEN-LAST:event_ViewBusActionPerformed

    /**
    * @param args the command line arguments
    */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainjFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MbusEntry;
    private javax.swing.JMenuItem McustEnquiry;
    private javax.swing.JMenuItem MrouteEntry;
    private javax.swing.JMenuItem ViewBus;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMainMenuBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables

}
