/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBusJInternalFrame.java
 *
 * Created on Oct 6, 2010, 12:33:09 AM
 */

package busticketbookingsystem;
import java.sql.*;
/**
 *
 * @author Hirak
 */
public class NewBusJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form NewBusJInternalFrame */
    public NewBusJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Save_Button = new javax.swing.JButton();
        Bus_ID_TextField = new javax.swing.JTextField();
        Route_ID_TextField = new javax.swing.JTextField();
        Total_Seats_TextField = new javax.swing.JTextField();
        Ticket_Price_TextField = new javax.swing.JTextField();

        setClosable(true);
        setTitle("New Bus Entry");
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bus_ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel2.setText("Route_ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel3.setText("Total Seats :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel4.setText("Ticket Price :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        getContentPane().add(Bus_ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, -1));

        Route_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Route_ID_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Route_ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, -1));
        getContentPane().add(Total_Seats_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, -1));

        Ticket_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ticket_Price_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Ticket_Price_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Route_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Route_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Route_ID_TextFieldActionPerformed

    private void Ticket_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ticket_Price_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ticket_Price_TextFieldActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:

        Connection con;
	Statement stmt;



		try{
   			Class.forName("oracle.jdbc.driver.OracleDriver");

   			con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:SCT","hirak","hirak123");


  			System.out.println("Got Connection");

  			stmt = con.createStatement();
                       
			System.out.println("Statement object created");
                       
   			stmt.executeQuery("insert into bus values('" + Bus_ID_TextField.getText()+"','"+Route_ID_TextField.getText()+"',"+Ticket_Price_TextField.getText()+","+Total_Seats_TextField.getText()+")");

		}//end of try

		catch(ClassNotFoundException e){
			System.out.println(e);
		}
		catch(SQLException e){
			System.out.println(e);
		}
		catch(Exception e){
			System.out.println(e);
		}
    }//GEN-LAST:event_Save_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bus_ID_TextField;
    private javax.swing.JTextField Route_ID_TextField;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField Ticket_Price_TextField;
    private javax.swing.JTextField Total_Seats_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
