/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewRouteJInternalFrame.java
 *
 * Created on Oct 6, 2010, 12:13:06 AM
 */

package busticketbookingsystem;
import java.sql.*;
/**
 *
 * @author Hirak
 */
public class NewRouteJInternalFrame extends javax.swing.JInternalFrame {

    /** Creates new form NewRouteJInternalFrame */
    public NewRouteJInternalFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bus_ID_TextField = new javax.swing.JTextField();
        Route_ID_TextField = new javax.swing.JTextField();
        Source_TextField = new javax.swing.JTextField();
        Destination_TextField = new javax.swing.JTextField();
        Total_seats_TextField = new javax.swing.JTextField();
        Ticket_price_TextField = new javax.swing.JTextField();
        Save_Button = new javax.swing.JButton();

        setClosable(true);
        setTitle("New Route Entry");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bus_ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("Route_ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Source :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Destination :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setText("Total Seats :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setText("Ticket Price :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        Bus_ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bus_ID_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Bus_ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, -1));
        getContentPane().add(Route_ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, -1));
        getContentPane().add(Source_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, -1));

        Destination_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destination_TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(Destination_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));
        getContentPane().add(Total_seats_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, -1));
        getContentPane().add(Ticket_price_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, -1));

        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Save_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bus_ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bus_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bus_ID_TextFieldActionPerformed

    private void Destination_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destination_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Destination_TextFieldActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:
        Connection con;
	Statement stmt,stmt2 ;



		try{
   			Class.forName("oracle.jdbc.driver.OracleDriver");

   			con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:SCT","hirak","hirak123");


  			System.out.println("Got Connection");

  			stmt = con.createStatement();
                        stmt2=con.createStatement();
			System.out.println("Statement object created");
                        stmt.executeQuery("insert into route values('" +Route_ID_TextField.getText()+"','"+Source_TextField.getText()+"','"+Destination_TextField.getText()+"')");
   			stmt.executeQuery("insert into bus values('" + Bus_ID_TextField.getText()+"','"+Route_ID_TextField.getText()+"',"+Ticket_price_TextField.getText()+","+Total_seats_TextField.getText()+")");

		}//end of try

		catch(ClassNotFoundException e){
			System.out.println(e);
		}
		catch(SQLException e){
			System.out.println(e);
		}
		catch(Exception e){
			System.out.println(e);
		}
    }//GEN-LAST:event_Save_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bus_ID_TextField;
    private javax.swing.JTextField Destination_TextField;
    private javax.swing.JTextField Route_ID_TextField;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField Source_TextField;
    private javax.swing.JTextField Ticket_price_TextField;
    private javax.swing.JTextField Total_seats_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
