tcc -1 -o1 add.c
tcc -2 -o2 add.c
tcc -C -oC add.c
tcc -G -oG add.c
tcc -K -oK add.c
tcc -M -oM add.c
tcc -O -oO add.c
tcc -N -oN add.c
tcc -P -oP add.c
tcc -S -oS add.c
tcc -X -oX add.c
tcc -Z -oZ add.c
tcc -a -oaa add.c
tcc -c -occ add.c
tcc -d -odd add.c
tcc -eadd -oee add.c
tcc -g1 -ogg add.c
tcc -i10 -oii add.c
tcc -j10 -ojj add.c
tcc -k -okk add.c
tcc -r -orr add.c
tcc -u -ouu add.c
tcc -v -ovv add.c
tcc -y -oyy add.c
tcc -oadd add.c