# standard names for the source directory and its subdirectories
CAZM	= /sim/cazm4.1/src/cazm/cazm


#############################################################################

all:	CAZMFILES

CAZMFILES:	ampbjtcur_cz ampjfetcur_cz ampmoscur_cz bjtbulk_cz \
		capvss_cz cur2_cz curbad_cz curbiti_cz curbitifloat_cz \
		curfloat_cz current_cz cursini_cz cursinifloat_cz curvc_cz \
		dio_cz  diog_cz indmutdot_cz indmutual_cz \
		indmutual2_cz indmutual3_cz indparallel_cz indseries_cz \
		indsub_cz indsub1_cz indsub2_cz indvdd_cz indvddeqv_cz \
		indvss_cz indvsseqv_cz volt_cz voltbit_cz \
		voltbitfloat_cz voltfloat_cz voltfloat2_cz \
		voltsin_cz voltsinfloat_cz voltvv_cz voltvvfloat_cz 

ampbjtcur_cz: ampbjtcur.cmd ampbjtcur.fa
	${CAZM} -o  ampbjtcur_cz  ampbjtcur
ampjfetcur_cz: ampjfetcur.cmd ampjfetcur.fa
	${CAZM} -o  ampjfetcur_cz  ampjfetcur
ampmoscur_cz: ampmoscur.cmd ampmoscur.fa
	${CAZM} -o  ampmoscur_cz  ampmoscur
bjtbulk_cz: bjtbulk.cmd bjtbulk.fa
	${CAZM} -o  bjtbulk_cz  bjtbulk
capvss_cz: capvss.cmd capvss.fa
	${CAZM} -o  capvss_cz  capvss
cur2_cz: cur2.cmd cur2.fa
	${CAZM} -o  cur2_cz  cur2
curbad_cz: curbad.cmd curbad.fa
	${CAZM} -o  curbad_cz  curbad
curbiti_cz: curbiti.cmd curbiti.fa
	${CAZM} -o  curbiti_cz  curbiti
curbitifloat_cz: curbitifloat.cmd curbitifloat.fa
	${CAZM} -o  curbitifloat_cz  curbitifloat
curfloat_cz: curfloat.cmd curfloat.fa
	${CAZM} -o  curfloat_cz  curfloat
current_cz: current.cmd current.fa
	${CAZM} -o  current_cz  current
cursini_cz: cursini.cmd cursini.fa
	${CAZM} -o  cursini_cz  cursini
cursinifloat_cz: cursinifloat.cmd cursinifloat.fa
	${CAZM} -o  cursinifloat_cz  cursinifloat
curvc_cz: curvc.cmd curvc.fa
	${CAZM} -o  curvc_cz  curvc
dio_cz: dio.cmd dio.fa
	${CAZM} -o  dio_cz  dio
diog_cz: diog.cmd diog.fa
	${CAZM} -o  diog_cz  diog
indmutdot_cz: indmutdot.cmd indmutdot.fa
	${CAZM} -o  indmutdot_cz  indmutdot
indmutual_cz: indmutual.cmd indmutual.fa
	${CAZM} -o  indmutual_cz  indmutual
indmutual2_cz: indmutual2.cmd indmutual2.fa
	${CAZM} -o  indmutual2_cz  indmutual2
indmutual3_cz: indmutual3.cmd indmutual3.fa
	${CAZM} -o  indmutual3_cz  indmutual3
indparallel_cz: indparallel.cmd indparallel.fa
	${CAZM} -o  indparallel_cz  indparallel
indseries_cz: indseries.cmd indseries.fa
	${CAZM} -o  indseries_cz  indseries
indsub_cz: indsub.cmd indsub.fa
	${CAZM} -o  indsub_cz  indsub
indsub1_cz: indsub1.cmd indsub1.fa
	${CAZM} -o  indsub1_cz  indsub1
indsub2_cz: indsub2.cmd indsub2.fa
	${CAZM} -o  indsub2_cz  indsub2
indvdd_cz: indvdd.cmd indvdd.fa
	${CAZM} -o  indvdd_cz  indvdd
indvddeqv_cz: indvddeqv.cmd indvddeqv.fa
	${CAZM} -o  indvddeqv_cz  indvddeqv
indvss_cz: indvss.cmd indvss.fa
	${CAZM} -o  indvss_cz  indvss
indvsseqv_cz: indvsseqv.cmd indvsseqv.fa
	${CAZM} -o  indvsseqv_cz  indvsseqv
volt_cz: volt.cmd volt.fa
	${CAZM} -o  volt_cz  volt
voltbit_cz: voltbit.cmd voltbit.fa
	${CAZM} -o  voltbit_cz  voltbit
voltbitfloat_cz: voltbitfloat.cmd voltbitfloat.fa
	${CAZM} -o  voltbitfloat_cz  voltbitfloat
voltfloat_cz: voltfloat.cmd voltfloat.fa
	${CAZM} -o  voltfloat_cz  voltfloat
voltfloat2_cz: voltfloat2.cmd voltfloat2.fa
	${CAZM} -o  voltfloat2_cz  voltfloat2
voltsin_cz: voltsin.cmd voltsin.fa
	${CAZM} -o  voltsin_cz  voltsin
voltsinfloat_cz: voltsinfloat.cmd voltsinfloat.fa
	${CAZM} -o  voltsinfloat_cz  voltsinfloat
voltvv_cz: voltvv.cmd voltvv.fa
	${CAZM} -o  voltvv_cz  voltvv
voltvvfloat_cz: voltvvfloat.cmd voltvvfloat.fa
	${CAZM} -o  voltvvfloat_cz  voltvvfloat

