            SUBROUTINE MOSEQ1(VDS,VBS,VGS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
C 
C     THIS ROUTINE EVALUATES THE DRAIN CURRENT AND ITS DERIVATIVES
C     USING THE SHICHMAN-HODGES MODEL AND THE CHARGES ASSOCIATED
C     WITH THE GATE, CHANNEL AND BULK FOR MOSFETS 
C 
      common /result/ Ueff,gammad,Xleff,Vbin,deltal,vth
      double precision phi,phib
      COMMON /MOSARG/ VTO,BETA,GAMMA,PHI,PHIB,COX,XNSUB,XNFS,XD,XJ,
     1   XLAMDA,UO,UEXP,VBP,UTRA,VMAX,XNEFF,XL,XW,VBI,VON,VDSAT,QSPOF,
     2   BETA0,BETA1,CDRAIN,XQCO,XQC,FNARRW,FSHORT
      COMMON /KNSTNT/ TWOPI,VT,CHARGE,EPSSIL,EPSOX,EGFET,XNI
C
      VBD=VBS-VDS 
      VGB=VGS-VBS 
C 
C 
      IF (VBS.GT.0.0D0) GO TO 102 
      SARG=DSQRT(PHI-VBS) 
      GO TO 104 
  102 SARG=DSQRT(PHI) 
      SARG=SARG-VBS/(SARG+SARG) 
      SARG=DMAX1(0.0D0,SARG)
  104 VON=VBI+GAMMA*SARG
      VGST=VGS-VON
      VDSAT=DMAX1(VGST,0.0D0) 
      IF (SARG.GT.0.0D0) GO TO 105
      ARG=0.0D0 
      GO TO 108 
  105 ARG=GAMMA/(SARG+SARG) 
  108 IF (VGST.GT.0.0D0) GO TO 110
C 
C     CUTOFF REGION 
C 
      CDRAIN=0.0D0
      GM=0.0D0
      GDS=0.0D0 
      GMBS=0.0D0
      GO TO 1000
C 
C     SATURATION REGION 
C 
  110 BETAP=BETA*(1.0D0+XLAMDA*VDS) 
      IF (VGST.GT.VDS) GO TO 120
      CDRAIN=BETAP*VGST*VGST*0.5D0
      GM=BETAP*VGST 
      GDS=XLAMDA*BETA*VGST*VGST*0.5D0 
      GMBS=GM*ARG 
      GO TO 1000
C 
C     LINEAR REGION 
C 
  120 CDRAIN=BETAP*VDS*(VGST-0.5D0*VDS) 
      GM=BETAP*VDS
      GDS=BETAP*(VGST-VDS)+XLAMDA*BETA*VDS*(VGST-0.5D0*VDS) 
      GMBS=GM*ARG 
C 
C     FINISHED
C 
 1000 RETURN
      END 
      SUBROUTINE MOSEQ2(VDS,VBS,VGS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
C 
C     THIS ROUTINE EVALUATES THE DRAIN CURRENT, ITS DERIVATIVES AND 
C     THE CHARGES ASSOCIATED WITH THE GATE, CHANNEL AND BULK
C     FOR MOSFETS 
C 
      common /result/ Ueff,gammad,Xleff,Vbin,deltal,vth
      double precision phi,phib
      COMMON /MOSARG/ VTO,BETA,GAMMA,PHI,PHIB,COX,XNSUB,XNFS,XD,XJ, 
     1   XLAMDA,UO,UEXP,VBP,UTRA,VMAX,XNEFF,XL,XW,VBI,VON,VDSAT,QSPOF,
     2   BETA0,BETA1,CDRAIN,XQCO,XQC,FNARRW,FSHORT
      COMMON /KNSTNT/ TWOPI,VT,CHARGE,EPSSIL,EPSOX,EGFET,XNI
C 
      DIMENSION A4(4),B4(4),X4(8),POLY4(8),SIG1(4),SIG2(4)
      DATA SIG1 / 1.0D0, -1.0D0, 1.0D0, -1.0D0/,
     1     SIG2 / 1.0D0,  1.0D0,-1.0D0, -1.0D0/ 
C 
C     ICHARG=1 CAUSES CHARGES TO BE COMPUTED
C     ICHARG=0 BYPASSES THE COMPUTATION OF CHARGES
C 
C      ICHARG=1
C      IF (MODE.NE.1.AND.XQCO.LE.0.5D0) GO TO 100
      ICHARG=0
C      IF (XQCO.GT.0.5D0) GO TO 100
C      IF (MODEDC.EQ.2.AND.NOSOLV.NE.0) ICHARG=1 
C      IF (INITF.EQ.4) ICHARG=1
C 
C  COMPUTE SOME USEFUL QUANTITIES 
C 
  100 IF (VBS.GT.0.0D0) GO TO 110 
      SARG=DSQRT(PHI-VBS) 
      TSARG=SARG+SARG 
      DSRGDB=-0.5D0/SARG
      D2SDB2=+0.5D0*DSRGDB/(PHI-VBS)
      GO TO 120 
  110 SPHI=DSQRT(PHI) 
      SPHI3=PHI*SPHI
      SARG=SPHI/(1.0D0+0.5D0*VBS/PHI) 
      TSARG=SARG+SARG 
      DSRGDB=-0.5D0*SARG*SARG/SPHI3 
      D2SDB2=-DSRGDB*SARG/SPHI3 
  120 IF ((VDS-VBS).LT.0.0D0) GO TO 130 
      BARG=DSQRT(PHI+VDS-VBS) 
      DBRGDB=-0.5D0/BARG
      D2BDB2=+0.5D0*DBRGDB/(PHI+VDS-VBS)
      GO TO 200 
  130 BARG=SPHI/(1.0D0+0.5D0*(VBS-VDS)/PHI) 
      DBRGDB=-0.5D0*BARG*BARG/SPHI3 
      D2BDB2=-DBRGDB*BARG/SPHI3 
C 
C  CALCULATE THRESHOLD VOLTAGE (VON)
C     NARROW-CHANNEL EFFECT 
C 
  200 FACTOR=0.125D0*FNARRW*TWOPI*EPSSIL/COX*XL 
      ETA=1.0D0+FACTOR
      VBIN=VBI+FACTOR*(PHI-VBS) 
      IF (GAMMA.LE.0.0D0) GO TO 215 
      IF (XNSUB.LE.0.0D0) GO TO 215 
      XWD=XD*BARG 
      XWS=XD*SARG 
C 
C     SHORT-CHANNEL EFFECT WITH VDS .NE. 0.0D0
C 
      ARGSS=0.0D0 
      ARGSD=0.0D0 
      DBARGS=0.0D0
      DBARGD=0.0D0
      DGDVDS=0.0D0
      DGDDB2=0.0D0
      IF (XJ.LE.0.0D0) GO TO 205
      ARGXS=1.0D0+2.0D0*XWS/XJ
      ARGS=DSQRT(ARGXS) 
      ARGSS=0.5D0*XJ/XL*(ARGS-1.0D0)
      ARGXD=1.0D0+2.0D0*XWD/XJ
      ARGD=DSQRT(ARGXD) 
      ARGSD=0.5D0*XJ/XL*(ARGD-1.0D0)
  205 GAMASD=GAMMA*(1.0D0-ARGSS-ARGSD)
      GAMASS=GAMMA*(1.0D0-2.0D0*ARGSS)
      DBXWD=XD*DBRGDB 
      DBXWS=XD*DSRGDB 
      IF (XJ.LE.0.0D0) GO TO 210
      DBARGS=0.5D0/XL*DBXWS/ARGS
      DBARGD=0.5D0/XL*DBXWD/ARGD
      DASDB2=-XD*( D2SDB2+DSRGDB*DSRGDB*XD/(XJ*ARGXS) )/(XL*ARGS) 
      DADDB2=-XD*( D2BDB2+DBRGDB*DBRGDB*XD/(XJ*ARGXD) )/(XL*ARGD) 
      DGDDB2=-0.5D0*GAMMA*(DASDB2+DADDB2) 
  210 DGDDVB=-GAMMA*(DBARGS+DBARGD) 
      DGSDVB=-2.0D0*GAMMA*DBARGS
      IF (XJ.LE.0.0D0) GO TO 220
      DDXWD=-DBXWD
      DGDVDS=-GAMMA*0.5D0/XL*DDXWD/ARGD 
      GO TO 220 
  215 GAMASD=GAMMA
      GAMASS=GAMMA
      GAMMAD=GAMMA
      DGDDVB=0.0D0
      DGSDVB=0.0D0
      DGDVDS=0.0D0
      DGDDB2=0.0D0
  220 VON=VBIN+GAMASD*SARG
C     WRITE(6,221) VON,VBIN,VBI,GAMASD,ARGSS,ARGSD,XJ 
  221 FORMAT ('0MSG1:'/1P7D10.2)
      VTH=VON 
      VDSAT=0.0D0 
  225 IF (XNFS.EQ.0.0D0.OR.COX.EQ.0.0D0) GO TO 230
      CFS=CHARGE*XNFS 
      CDONCO=-(GAMASD*DSRGDB+DGDDVB*SARG)+FACTOR
      XN=1.0D0+CFS/COX*XW*XL+CDONCO 
      VON=VON+VT*XN 
C     WRITE (6,226) VON,CDONCO,XN,CFS,XD
  226 FORMAT(' MSG2:'/1P6D10.2) 
      ARGG=1.0D0/(VT*XN)
      VGST=VGS-VON
      GO TO 300 
  230 VGST=VGS-VON
      IF (VGS.GT.VON) GO TO 300 
C 
C  CUTOFF REGION
C 
      GDS=0.0D0 
      GO TO 1050
C 
C  COMPUTE SOME MORE USEFUL QUANTITIES
C 
  300 SARG3=SARG*SARG*SARG
      SBIARG=DSQRT(PHIB)
      GAMMAD=GAMASD 
      DGDVBS=DGDDVB 
      BODY=BARG*BARG*BARG-SARG3 
      GDBDV=2.0D0*GAMMAD*(BARG*BARG*DBRGDB-SARG*SARG*DSRGDB)
      DODVBS=-FACTOR+DGDVBS*SARG+GAMMAD*DSRGDB
      IF (XNFS.EQ.0.0D0) GO TO 400
      IF (COX.EQ.0.0D0) GO TO 410 
      DXNDVB=2.0D0*DGDVBS*DSRGDB+GAMMAD*D2SDB2+DGDDB2*SARG
      DODVBS=DODVBS+VT*DXNDVB 
      DXNDVD=DGDVDS*DSRGDB
      DODVDS=DGDVDS*SARG+VT*DXNDVD
C 
C  EVALUATE EFFECTIVE MOBILITY AND ITS DERIVATIVES
C 
  400 IF (COX.LE.0.0D0) GO TO 410 
      UDENOM=VGST 
      IF (UDENOM.LE.VBP) GO TO 410
      UFACT=DEXP(UEXP*DLOG(VBP/UDENOM)) 
      UEFF=UO*UFACT 
      DUDVGS=-UFACT*UEXP/UDENOM 
      DUDVDS=0.0D0
      DUDVBS=UEXP*UFACT*DODVBS/VGST 
      GO TO 500 
  410 UFACT=1.0D0 
      UEFF=UO 
      DUDVGS=0.0D0
      DUDVDS=0.0D0
      DUDVBS=0.0D0
C 
C     EVALUATE SATURATION VOLTAGE AND ITS DERIVATIVES ACCORDING TO
C     GROVE-FROHMAN EQUATION
C 
  500 VGSX=VGS
      GAMMAD=GAMASD/ETA 
      DGDVBS=DGDDVB 
      IF (XNFS.NE.0.0D0.AND.COX.NE.0.0D0) 
     1   VGSX=DMAX1(VGS,VON)
  505 IF (GAMMAD.LE.0.0D0) GO TO 535
      GAMMD2=GAMMAD*GAMMAD
      ARGV=(VGSX-VBIN)/ETA+PHI-VBS
      IF (ARGV.LE.0.0D0) GO TO 540
      ARG=DSQRT(1.0D0+4.0D0*ARGV/GAMMD2)
      VDSAT=(VGSX-VBIN)/ETA+GAMMD2*(1.0D0-ARG)/2.0D0
      VDSAT=DMAX1(VDSAT,0.0D0)
  510 IF (ICHARG.EQ.0) GO TO 530
      ARG1=GAMMD2/(ETA*ETA) 
      ARG2=VDS-0.5D0*ARG1 
      ARGSQ=(ARG2+0.5D0*ARG1+PHI-VBS)*ARG1
      IF (ARGSQ.GE.0.0D0) GO TO 515 
      VPOF=VTH
      GO TO 520 
  515 VPOF=VBIN+ETA*(ARG2+0.5D0*ARG1+DSQRT(ARGSQ))
  520 ARGV1=(VPOF-VBIN)/ETA+PHI-VBS 
      IF (ARGV1.GT.0.0D0) GO TO 525 
      VDSAT1=0.0D0
      GO TO 530 
  525 ARG1=DSQRT(1.0D0+4.0D0*ARGV1/GAMMD2)
      VDSAT1=(VPOF-VBIN)/ETA+GAMMD2*(1.0D0-ARG1)/2.0D0
      VDSAT1=DMAX1(VDSAT1,0.0D0)
  530 DSDVGS=(1.0D0-1.0D0/ARG)/ETA
      DSDVBS=(GAMMAD*(1.0D0-ARG)+2.0D0*ARGV/(GAMMAD*ARG))/ETA*DGDVBS+ 
     1       1.0D0/ARG+FACTOR*DSDVGS
      GO TO 545 
  535 VDSAT=DMAX1((VGSX-VBIN)/ETA,0.0D0)
      VPOF=DMAX1((ETA*VDS+VBIN),0.0D0)
      VDSAT1=DMAX1((VPOF-VBIN)/ETA,0.0D0) 
      DSDVGS=1.0D0
      DSDVBS=0.0D0
      GO TO 545 
  540 VDSAT=0.0D0 
      VPOF=VTH
      VDSAT1=0.0D0
      DSDVGS=0.0D0
      DSDVBS=0.0D0
C 
C     STORE VDSAT AS ABOVE IN VPOF (PINCH-OFF)
C 
  545 IF (VMAX.LE.0.0D0) GO TO 600
C 
C     EVALUATE SATURATION VOLTAGE AND ITS DERIVATIVES ACCORDING TO
C     BAUM'S THEORY OF SCATTERING VELOCITY SATURATION 
C 
      GAMMD2=GAMMAD*GAMMAD
      V1=(VGSX-VBIN)/ETA+PHI-VBS
      V2=PHI-VBS
      XV=VMAX*XL/UEFF 
      A1=GAMMAD/0.75D0
      B1=-2.0D0*(V1+XV) 
      C1=-2.0D0*GAMMAD*XV 
      D1=2.0D0*V1*(V2+XV)-V2*V2-4.0D0/3.0D0*GAMMAD*SARG3
      A=-B1 
      B=A1*C1-4.0D0*D1
      C=-D1*(A1*A1-4.0D0*B1)-C1*C1
      R=-A*A/3.0D0+B
      S=2.0D0*A*A*A/27.0D0-A*B/3.0D0+C
      R3=R*R*R
      S2=S*S
      P=S2/4.0D0+R3/27.0D0
      P0=DABS(P)
      P2=DSQRT(P0)
      IF (P.GE.0.0D0) GO TO 550 
      RO=DSQRT(S2/4.0D0+P0) 
      RO=DLOG(RO)/3.0D0 
      RO=DEXP(RO) 
      FI=DATAN(-2.0D0*P2/S) 
      Y3=2.0D0*RO*DCOS(FI/3.0D0)-A/3.0D0
      GO TO 560 
  550 P3=DEXP(DLOG(DABS(-S/2.0D0+P2))/3.0D0)
      P4=DEXP(DLOG(DABS(-S/2.0D0-P2))/3.0D0)
      Y3=P3+P4-A/3.0D0
  560 IKNT=0
      A3=DSQRT(A1*A1/4.0D0-B1+Y3) 
      if (dabs(y3*y3/4.d0-d1).le.1.d-10*d1) then
          B3=0.d0
          go to 5555
      endif
      B3=DSQRT(Y3*Y3/4.0D0-D1)
5555  DO 570 I=1,4
      A4(I)=A1/2.0D0+SIG1(I)*A3 
      B4(I)=Y3/2.0D0+SIG2(I)*B3 
      DELTA4=A4(I)*A4(I)/4.0D0-B4(I)
      IF (DELTA4.LT.0.0D0) GO TO 570
      IKNT=IKNT+1 
      X4(IKNT)=-A4(I)/2.0D0+DSQRT(DELTA4) 
      IKNT=IKNT+1 
      X4(IKNT)=-A4(I)/2.0D0-DSQRT(DELTA4) 
  570 CONTINUE
      JKNT=0
      DO 580 J=1,IKNT 
      IF (X4(J).LE.0.0D0) GO TO 580 
      POLY4(J)=X4(J)*X4(J)*X4(J)*X4(J)+A1*X4(J)*X4(J)*X4(J) 
      POLY4(J)=POLY4(J)+B1*X4(J)*X4(J)+C1*X4(J)+D1
      IF (DABS(POLY4(J)).GT.1.0D-6) GO TO 580 
      JKNT=JKNT+1 
      IF (JKNT.GT.1) GO TO 575
      XVALID=X4(J)
  575 IF (X4(J).GT.XVALID) GO TO 580
      XVALID=X4(J)
  580 CONTINUE
      IF (JKNT.GT.0) GO TO 590
      IVMFLG=IVMFLG+1 
      GO TO 600 
  590 VDSAT=XVALID*XVALID+VBS-PHI 
C 
C  EVALUATE EFFECTIVE CHANNEL LENGTH AND ITS DERIVATIVES
C 
  600 IF (VDS.EQ.0.0D0) GO TO 610 
      GAMMAD=GAMASD 
      IF ((VBS-VDSAT).GT.0.0D0) GO TO 601 
      BSARG=DSQRT(VDSAT-VBS+PHI)
      DBSRDB=-0.5D0/BSARG 
      GO TO 602 
  601 BSARG=SPHI/(1.0D0+0.5D0*(VBS-VDSAT)/PHI)
      DBSRDB=-0.5D0*BSARG*BSARG/SPHI3 
  602 BODYS=BSARG*BSARG*BSARG-SARG3 
      GDBDVS=2.0D0*GAMMAD*(BSARG*BSARG*DBSRDB-SARG*SARG*DSRGDB) 
      IF (VMAX.GT.0.0D0) GO TO 603
      IF (XNSUB.EQ.0.0D0) GO TO 610 
      IF (XLAMDA.GT.0.0D0) GO TO 610
      ARGV=(VDS-VDSAT)/4.0D0
      SARGV=DSQRT(1.0D0+ARGV*ARGV)
      ARG=DSQRT(ARGV+SARGV) 
      XLFACT=XD/(XL*VDS)
      XLAMDA=XLFACT*ARG 
      DLDSAT=VDS*XLFACT*ARG/(8.0D0*SARGV) 
      GO TO 605 
  603 ARGV=(VGSX-VBIN)/ETA-VDSAT
      XDV=XD/DSQRT(XNEFF) 
      XLV=VMAX*XDV/(2.0D0*UEFF) 
      VQCHAN=ARGV-GAMMAD*BSARG
      DQDSAT=-1.0D0+GAMMAD*DBSRDB 
      VL=VMAX*XL
      DFUNDS=VL*DQDSAT-UEFF*VQCHAN
      DFUNDG=(VL-UEFF*VDSAT)/ETA
      DFUNDB=-VL*(1.0D0+DQDSAT-FACTOR/ETA)+ 
     1        UEFF*(GDBDVS-DGDVBS*BODYS/1.5D0)/ETA
      DSDVGS=-DFUNDG/DFUNDS 
      DSDVBS=-DFUNDB/DFUNDS 
      IF (XNSUB.EQ.0.0D0) GO TO 610 
      IF (XLAMDA.GT.0.0D0) GO TO 610
      ARGV=DMAX1(VDS-VDSAT,0.0D0) 
      XLS=DSQRT(XLV*XLV+ARGV) 
      DLDSAT=XDV/(2.0D0*XLS)
      XLFACT=XDV/(XL*VDS) 
      XLAMDA=XLFACT*(XLS-XLV) 
      DLDSAT=DLDSAT/XL
  605 DLDVGS=DLDSAT*DSDVGS
      DLDVDS=-XLAMDA+DLDSAT 
      DLDVBS=DLDSAT*DSDVBS
      GO TO 620 
  610 DLDVGS=0.0D0
      DLDVDS=0.0D0
      DLDVBS=0.0D0
C 
C     LIMIT CHANNEL SHORTENING AT PUNCH-THROUGH 
C 
  620 XWB=XD*SBIARG 
      XLD=XL-XWB
      CLFACT=1.0D0-XLAMDA*VDS 
      DLDVDS=-XLAMDA-DLDVDS 
      XLEFF=XL*CLFACT 
      DELTAL=XLAMDA*VDS*XL
      IF (XNSUB.EQ.0.0D0) XWB=0.25D-6 
      IF (XLEFF.GE.XWB) GO TO 700 
      XLEFF=XWB/(1.0D0+(DELTAL-XLD)/XWB)
      CLFACT=XLEFF/XL 
      DFACT=XLEFF*XLEFF/(XWB*XWB) 
      DLDVGS=DFACT*DLDVGS 
      DLDVDS=DFACT*DLDVDS 
      DLDVBS=DFACT*DLDVBS 
C 
C  EVALUATE EFFECTIVE BETA (EFFECTIVE KP) 
C 
  700 BETA1=BETA*UFACT/CLFACT 
C 
C  TEST FOR MODE OF OPERATION AND BRANCH APPROPRIATELY
C 
      GAMMAD=GAMASD 
      DGDVBS=DGDDVB 
      IF (VDS.GT.1.0D-8) GO TO 730
      IF (VGS.GT.VON) GO TO 720 
      IF ((XNFS.NE.0.0D0).AND.(COX.NE.0.0D0)) GO TO 710 
      GDS=0.0D0 
      GO TO 1050
C 
  710 GDS=BETA1*(VON-VBIN-GAMMAD*SARG)*DEXP(ARGG*(VGS-VON)) 
      GO TO 1050
C 
C 
  720 GDS=BETA1*(VGS-VBIN-GAMMAD*SARG)
      GO TO 1050
C 
  730 IF (VGS.GT.VON) GO TO 900 
C 
C  SUBTHRESHOLD REGION
C 
      IF (VDSAT.GT.0.0D0) GO TO 830 
      GDS=0.0D0 
      IF (VGS.GT.VTH) GO TO 1020
      GO TO 1050
  830 VDSON=DMIN1(VDSAT,VDS)
      IF (VDS.LE.VDSAT) GO TO 850 
      BARG=BSARG
      DBRGDB=DBSRDB 
      BODY=BODYS
      GDBDV=GDBDVS
  850 CDSON=BETA1*((VON-VBIN-ETA*VDSON*0.5D0)*VDSON-GAMMAD*BODY/1.5D0)
      DIDVDS=BETA1*(VON-VBIN-ETA*VDSON-GAMMAD*BARG) 
      GDSON=-CDSON*DLDVDS/CLFACT-BETA1*DGDVDS*BODY/1.5D0
      IF (VDS.LT.VDSAT) GDSON=GDSON+DIDVDS
      GBSON=-CDSON*DLDVBS/CLFACT
     1      +BETA1*(DODVBS*VDSON+FACTOR*VDSON-DGDVBS*BODY/1.5D0-GDBDV)
      IF (VDS.GT.VDSAT) GBSON=GBSON+DIDVDS*DSDVBS 
      EXPG=DEXP(ARGG*(VGS-VON)) 
      CDRAIN=CDSON*EXPG 
      GMW=CDRAIN*ARGG 
      GM=GMW
      IF (VDS.GT.VDSAT) GM=GMW+DIDVDS*DSDVGS*EXPG 
      GDS=GDSON*EXPG-GM*DODVDS-GMW*(VGS-VON)*DXNDVD/XN
      GMBS=GBSON*EXPG-GM*DODVBS-GMW*(VGS-VON)*DXNDVB/XN 
      GO TO 1020
C 
C 
  900 IF (VDS.GT.VDSAT) GO TO 1000
C 
C  LINEAR REGION
C 
      CDRAIN=BETA1*((VGS-VBIN-ETA*VDS/2.0D0)*VDS-GAMMAD*BODY/1.5D0) 
      ARG=CDRAIN*(DUDVGS/UFACT-DLDVGS/CLFACT) 
      GM=ARG+BETA1*VDS
      ARG=CDRAIN*(DUDVDS/UFACT-DLDVDS/CLFACT) 
      GDS=ARG+BETA1*(VGS-VBIN-ETA*VDS-
     1   GAMMAD*BARG-DGDVDS*BODY/1.5D0) 
      ARG=CDRAIN*(DUDVBS/UFACT-DLDVBS/CLFACT) 
      GMBS=ARG-BETA1*(GDBDV+DGDVBS*BODY/1.5D0-FACTOR*VDS) 
      GO TO 1020
C 
C  SATURATION REGION
C 
 1000 CDRAIN=BETA1*((VGS-VBIN-ETA*VDSAT/2.0D0)*VDSAT-GAMMAD*BODYS/1.5D0)
      ARG=CDRAIN*(DUDVGS/UFACT-DLDVGS/CLFACT) 
      GM=ARG+BETA1*VDSAT+ 
     1   BETA1*(VGS-VBIN-ETA*VDSAT-GAMMAD*BSARG)*DSDVGS 
      GDS=-CDRAIN*DLDVDS/CLFACT-BETA1*DGDVDS*BODYS/1.5D0
      ARG=CDRAIN*(DUDVBS/UFACT-DLDVBS/CLFACT) 
      GMBS=ARG-BETA1*(GDBDVS+DGDVBS*BODYS/1.5D0-FACTOR*VDSAT)+
     1     BETA1*(VGS-VBIN-ETA*VDSAT-GAMMAD*BSARG)*DSDVBS 
C 
C     COMPUTE CHARGES FOR 'ON' REGION 
C 
 1020 IF (ICHARG.EQ.0) GO TO 1500 
C      IF (VGS.LE.VTH) GO TO 1070
C      CALL MQSPOF(VDS,VBS,VGS,VPOF,VDSAT1,VTH,VBIN,GAMASD,
C     1   QG,QC,QB,CGGB,CGDB,CGSB,CBGB,CBDB,CBSB)
C      GO TO 2000
C 
C  FINISH SPECIAL CASES 
C 
 1050 CDRAIN=0.0D0
      GM=0.0D0
      GMBS=0.0D0
C 1070 XQC=XQCO
C      IF (ICHARG.EQ.0) GO TO 1500 
C      CALL MOSQ2(VDS,VBS,VGS,VDSAT,VTH,VBIN,GAMASD,COX,PHI, 
C     1   QG,QC,QB,CGGB,CGDB,CGSB,CBGB,CBDB,CBSB)
C      QSPOF=0.0D0 
C      GO TO 2000
C 
C  FINISHED 
C 
 1500 QG=0.0D0
      QB=0.0D0
      QC=0.0D0
      QSPOF=0.0D0 
 2000 RETURN
      END 
      SUBROUTINE MOSEQ3(VDS,VBS,VGS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z) 
C 
C     THIS ROUTINE EVALUATES THE DRAIN CURRENT, ITS DERIVATIVES AND 
C     THE CHARGES ASSOCIATED WITH THE GATE, CHANNEL AND BULK
C     FOR MOSFETS BASED ON SEMI-EMPIRICAL EQUATIONS 
C 
      common /result/ Ueff,gammad,Xleff,Vbin,deltal,vth
      double precision phi,phib
      COMMON /MOSARG/ VTO,BETA,GAMMA,PHI,PHIB,COX,XNSUB,XNFS,XD,XJ, 
     1   XLAMDA,UO,UEXP,VBP,UTRA,VMAX,XNEFF,XL,XW,VBI,VON,VDSAT,QSPOF,
     2   BETA0,BETA1,CDRAIN,XQCO,XQC,FNARRW,FSHORT
      COMMON /KNSTNT/ TWOPI,VT,CHARGE,EPSSIL,EPSOX,EGFET,XNI
C 
      EQUIVALENCE (XLAMDA,ALPHA),(VBP,THETA),(UTRA,XKAPPA) 
      DATA COEFF0/0.0631353D0/,COEFF1/0.8013292D0/,COEFF2/-0.01110777D0/
C 
C     ICHARG=1 CAUSES CHARGES TO BE COMPUTED
C     ICHARG=0 BYPASSES THE COMPUTATION OF CHARGES
C 
C     ICHARG=1
C     IF (MODE.NE.1) GO TO 10 
C     ICHARG=0
C     IF (MODEDC.EQ.2.AND.NOSOLV.NE.0) ICHARG=1 
C     IF (INITF.EQ.4) ICHARG=1
C 
C     REFERENCE CDRAIN EQUATIONS TO SOURCE AND
C     CHARGE EQUATIONS TO BULK
C 
      ETA=UEXP
10    CONTINUE
      ICHARG=0
      VGB=VGS-VBS 
      VFB=VBI-PHI 
      VDSAT=0.0D0 
      QG=0.0D0
      QB=0.0D0
      QC=0.0D0
      CGDB=0.0D0
      CBDB=0.0D0
      ONXL=1.0D0/XL 
      ETA=ETA/(XL*XL*XL)
C 
C.....SQUARE ROOT TERM
C 
      IF ( VBS.GT.0.0D0 ) GO TO 120 
      PHIBS=PHI-VBS 
      SQPHBS=DSQRT(PHIBS) 
      DSQDVB=-0.5D0/SQPHBS
      GO TO 200 
120   CONTINUE
      SQPHIS=DSQRT(PHI) 
      SQPHS3=PHI*SQPHIS 
      SQPHBS=SQPHIS/(1.0D0+VBS/(PHI+PHI)) 
      PHIBS=SQPHBS*SQPHBS 
      DSQDVB=-PHIBS/(SQPHS3+SQPHS3) 
C 
C.....SHORT CHANNEL EFFECT FACTOR 
C 
200   CONTINUE
      IF ( (XJ.EQ.0.0D0).OR.(XD.EQ.0.0D0) ) GO TO 210 
      WPS=XD*SQPHBS 
      ONXJ=1.0D0/XJ 
      XJONXL=XJ*ONXL
      DJONXJ=XLD*ONXJ 
      WPONXJ=WPS*ONXJ 
      WCONXJ=COEFF0+COEFF1*WPONXJ+COEFF2*WPONXJ*WPONXJ
      WCS=WCONXJ*XJ 
      ARGA=WCONXJ+DJONXJ
      ARGC=WPONXJ/(1.0D0+WPONXJ)
      ARGB=DSQRT(1.0D0-ARGC*ARGC) 
      FSHORT=1.0D0-XJONXL*(ARGA*ARGB-DJONXJ)
      DWPDVB=XD*DSQDVB
      DADVB=(COEFF1+COEFF2*(WPONXJ+WPONXJ))*DWPDVB*ONXJ 
      DBDVB=-ARGC*ARGC*(1.0D0-ARGC)*DWPDVB/(ARGB*WPS) 
      DFSDVB=-XJONXL*(DADVB*ARGB+ARGA*DBDVB)
      GO TO 220 
210   CONTINUE
      FSHORT=1.0D0
      DFSDVB=0.0D0
      WCS=0.05D-6 
C 
C.....BODY EFFECT 
C 
220   CONTINUE
      GAMMAS=GAMMA*FSHORT 
      FBODYS=0.5D0*GAMMAS/(SQPHBS+SQPHBS) 
      FBODY=FBODYS+FNARRW 
      ONFBDY=1.0D0/(1.0D0+FBODY)
      DFBDVB=-FBODYS*DSQDVB/SQPHBS+FBODYS*DFSDVB/FSHORT 
      QBONCO=GAMMAS*SQPHBS+FNARRW*PHIBS 
      DQBDVB=GAMMAS*DSQDVB+GAMMA*DFSDVB*SQPHBS-FNARRW 
C 
C.....STATIC FEEDBACK EFFECT
C 
      VBIX=VBI-ETA*VDS
C 
C.....THRESHOLD VOLTAGE 
C 
      VTH=VBIX+QBONCO 
      DVTDVD=-ETA 
      DVTDVB=DQBDVB 
C 
C.....JOINT WEAK INVERSION AND STRONG INVERSION 
C 
      VON=VTH 
      IF ( XNFS.EQ.0.0D0 ) GO TO 250
           CSONCO=CHARGE*XNFS*XL*XW/COX 
           CDONCO=QBONCO/(PHIBS+PHIBS)
           XN=1.0D0+CSONCO+CDONCO 
           VON=VTH+VT*XN
           DXNDVB=DQBDVB/(PHIBS+PHIBS)-QBONCO*DSQDVB/(PHIBS*SQPHBS) 
           DVODVD=DVTDVD
           DVODVB=DVTDVB+VT*DXNDVB
           GO TO 300
C 
C.....CUTOFF REGION 
C 
250   CONTINUE
      IF ( VGS.GT.VON ) GO TO 300 
      CDRAIN=0.0D0
      GM=0.0D0
      GDS=0.0D0 
      GMBS=0.0D0
      IF ( ICHARG.NE.0 ) GO TO 800
      GO TO 1000
C 
C.....DEVICE IS ON
C 
300   CONTINUE
      VGSX=DMAX1(VGS,VON) 
C 
C.....MOBILITY MODULATION BY GATE VOLTAGE 
C 
      ONFG=1.0D0+THETA*(VGSX-VTH) 
      FGATE=1.0D0/ONFG
      US=UO*FGATE 
      DFGDVG=-THETA*FGATE*FGATE 
      DFGDVD=-DFGDVG*DVTDVD 
      DFGDVB=-DFGDVG*DVTDVB 
C 
C.....SATURATION VOLTAGE
C 
      VDSAT=(VGSX-VTH)*ONFBDY 
      VPOF=VDSAT
      IF ( VMAX.GT.0.0D0 ) GO TO 310
      DVSDVG=ONFBDY 
      DVSDVD=-DVSDVG*DVTDVD 
      DVSDVB=-DVSDVG*DVTDVB-VDSAT*DFBDVB*ONFBDY 
      GO TO 400 
  310 VDSC=XL*VMAX/US 
      ONVDSC=1.0D0/VDSC 
      ARGA=(VGSX-VTH)*ONFBDY
      ARGB=DSQRT(ARGA*ARGA+VDSC*VDSC) 
      VDSAT=ARGA+VDSC-ARGB
      DVSDGA=(1.0D0-ARGA/ARGB)*ONFBDY 
      DVSDVG=DVSDGA-(1.0D0-VDSC/ARGB)*VDSC*DFGDVG*ONFG
      DVSDVD=-DVSDVG*DVTDVD 
      DVSDVB=-DVSDVG*DVTDVB-ARGA*DVSDGA*DFBDVB
C 
C.....CURRENT FACTORS IN LINEAR REGION
C 
400   CONTINUE
      VDSX=DMIN1(VDS,VDSAT) 
      IF ( VDSX.EQ.0.0D0 ) GO TO 900
      CDO=VGSX-VTH-0.5D0*(1.0D0+FBODY)*VDSX 
      DCODVG=1.0D0
      IF (VDS.LT.VDSAT) DCODVD=-DVTDVD-0.5D0*(1.0D0+FBODY)
      DCODVB=-DVTDVB-0.5D0*DFBDVB*VDSX
C 
C.....NORMALIZED DRAIN CURRENT
C 
410   CONTINUE
      CDNORM=CDO*VDSX 
      GM=VDSX 
      GDS=VGSX-VTH-(1.0D0+FBODY+DVTDVD)*VDSX
      GMBS=DCODVB*VDSX
C 
C.....DRAIN CURRENT WITHOUT VELOCITY SATURATION EFFECT
C 
      CD1=BETA*CDNORM 
      BETA=BETA*FGATE 
      CDRAIN=BETA*CDNORM
      GM=BETA*GM+DFGDVG*CD1 
      GDS=BETA*GDS+DFGDVD*CD1 
      GMBS=BETA*GMBS
C 
C.....VELOCITY SATURATION FACTOR
C 
      IF ( VMAX.EQ.0.0D0 ) GO TO 500
      FDRAIN=1.0D0/(1.0D0+VDSX*ONVDSC)
      FD2=FDRAIN*FDRAIN 
      ARGA=FD2*VDSX*ONVDSC*ONFG 
      DFDDVG=-DFGDVG*ARGA 
      DFDDVD=-DFGDVD*ARGA-FD2*ONVDSC
      DFDDVB=-DFGDVB*ARGA 
C 
C.....DRAIN CURRENT 
C 
      GM=FDRAIN*GM+DFDDVG*CDRAIN
      GDS=FDRAIN*GDS+DFDDVD*CDRAIN
      GMBS=FDRAIN*GMBS+DFDDVB*CDRAIN
      CDRAIN=FDRAIN*CDRAIN
      BETA=BETA*FDRAIN
C 
C.....CHANNEL LENGTH MODULATION 
C 
500   CONTINUE
      IF ( VDS.LE.VDSAT ) GO TO 700 
      IF ( VMAX.EQ.0.0D0 ) GO TO 510
      IF (ALPHA.EQ.0.0D0) GO TO 700 
      CDSAT=CDRAIN
      GDSAT=CDSAT*(1.0D0-FDRAIN)*ONVDSC 
      GDSAT=DMAX1(1.0D-12,GDSAT)
      GDONCD=GDSAT/CDSAT
      GDONFD=GDSAT/(1.0D0-FDRAIN) 
      GDONFG=GDSAT*ONFG 
      DGDVG=GDONCD*GM-GDONFD*DFDDVG+GDONFG*DFGDVG 
      DGDVD=GDONCD*GDS-GDONFD*DFDDVD+GDONFG*DFGDVD
      DGDVB=GDONCD*GMBS-GDONFD*DFDDVB+GDONFG*DFGDVB 
C 
      EMAX=CDSAT*ONXL/GDSAT 
      EMONCD=EMAX/CDSAT 
      EMONGD=EMAX/GDSAT 
      DEMDVG=EMONCD*GM-EMONGD*DGDVG 
      DEMDVD=EMONCD*GDS-EMONGD*DGDVD
      DEMDVB=EMONCD*GMBS-EMONGD*DGDVB 
C 
      ARGA=0.5D0*EMAX*ALPHA 
      ARGC=XKAPPA*ALPHA 
      ARGB=DSQRT(ARGA*ARGA+ARGC*(VDS-VDSAT))
      DELXL=ARGB-ARGA 
      DLDVD=ARGC/(ARGB+ARGB)
      DLDEM=0.5D0*(ARGA/ARGB-1.0D0)*ALPHA 
      DDLDVG=DLDEM*DEMDVG 
      DDLDVD=DLDEM*DEMDVD-DLDVD 
      DDLDVB=DLDEM*DEMDVB 
      GO TO 520 
510   CONTINUE
      DELXL=DSQRT(XKAPPA*(VDS-VDSAT)*ALPHA) 
      DLDVD=0.5D0*DELXL/(VDS-VDSAT) 
      DDLDVG=0.0D0
      DDLDVD=-DLDVD 
      DDLDVB=0.0D0
C 
C.....PUNCH THROUGH APPROXIMATION 
C 
520   CONTINUE
      IF ( DELXL.LE.(0.5D0*XL) ) GO TO 600
      WCS2=WCS*WCS
      DELXL=XL-(XL**2/(4.0D0*DELXL))
      ARGA=4.0D0*(XL-DELXL)**2/XL**2
      DDLDVG=DDLDVG*ARGA
      DDLDVD=DDLDVD*ARGA
      DDLDVB=DDLDVB*ARGA
       DLDVD= DLDVD*ARGA
C 
C.....SATURATION REGION 
C 
600   CONTINUE
      DLONXL=DELXL*ONXL 
      XLFACT=1.0D0/(1.0D0-DLONXL) 
      CDRAIN=CDRAIN*XLFACT
      DIDDL=CDRAIN/(XL-DELXL) 
      GM=GM*XLFACT+DIDDL*DDLDVG 
      GDS0=GDS*XLFACT+DIDDL*DDLDVD
      GMBS=GMBS*XLFACT+DIDDL*DDLDVB 
      GM=GM+GDS0*DVSDVG 
      GMBS=GMBS+GDS0*DVSDVB 
      GDS=GDS0*DVSDVD+DIDDL*DLDVD 
C 
C.....FINISH STRONG INVERSION CASE
C 
700   CONTINUE
      IF ( VGS.GE.VON ) GO TO 750 
C 
C.....WEAK INVERSION
C 
                ONXN=1.0D0/XN 
                ONDVT=ONXN/VT 
                WFACT=DEXP( (VGS-VON)*ONDVT ) 
                CDRAIN=CDRAIN*WFACT 
                GMS=GM*WFACT
                GMW=CDRAIN*ONDVT
                GM=GMW
                IF (VDS.GT.VDSAT) GM=GM+GDS0*DVSDVG*WFACT 
                GDS=GDS*WFACT+(GMS-GMW)*DVODVD
                GMBS=GMBS*WFACT+(GMS-GMW)*DVODVB
     1                         -GMW*(VGS-VON)*ONXN*DXNDVB 
C 
C.....CHARGE COMPUTATION
C 
  750 CONTINUE
      IF (ICHARG.EQ.0) GO TO 1000 
C      IF (VGS.LE.VTH) GO TO 800 
C      CALL MQSPOF(VDS,VBS,VGS,VPOF,VDSAT1,VTH,VBIN,GAMASD,
C     1   QG,QC,QB,CGGB,CGDB,CGSB,CBGB,CBDB,CBSB)
C      GO TO 2000
C 
C.....CHARGE COMPUTATION FOR VGS<VTH
C 
800   CONTINUE
C      XQC=XQCO
C      CALL MOSQ3(VDS,VBS,VPOF,VDSAT1,VTH,VBIN,GAMASD,COX,PHI, 
C     1   QG,QC,QB,CGGB,CGDB,CGSB,CBGB,CBDB,CBSB)
C      QSPOF=0.0D0 
      GO TO 2000
C 
C.....SPECIAL CASE OF VDS=0.0D0 
C 
900   CONTINUE
      BETA=BETA*FGATE 
      CDRAIN=0.0D0
      GM=0.0D0
      GDS=BETA*(VGSX-VTH) 
      GMBS=0.0D0
           IF ( (XNFS.NE.0.0D0).AND.(VGS.LT.VON) )
     1          GDS=GDS*DEXP((VGS-VON)/(VT*XN)) 
C      IF (ICHARG.EQ.0) GO TO 1000 
C      CALL MOSQ3(VDS,VBS,VPOF,VDSAT1,VTH,VBIN,GAMASD,COX,PHI, 
C     1   QG,QC,QB,CGGB,CGDB,CGSB,CBGB,CBDB,CBSB)
1000  QSPOF=0.0D0 
C 
C.....DONE
C 
 2000 RETURN
      END 

