#! /bin/csh -f

foreach i (6.0 5.9 5.8 5.7 5.6 5.5 5.4 5.3 5.2 5.1 5.0 \
	       4.9 4.8 4.7 4.6 4.5 4.4 4.3 4.2 4.1 4.0 \
	       3.9 3.8 3.7 3.6 3.5 3.4 3.3 3.2 3.1 3.0 \
	       2.9 2.8 2.7 2.6 2.5 2.4 2.3 2.2 2.1 2.0)

#    cat test.awk | sed s/XXX/$i/ >! 1.awk
#    awk -f 1.awk ring11_$i.out >> data

     cat inter.awk | sed s/XXX/$i/ >! 2.awk
     awk -f 2.awk ring11_$i.out >> data1
end
