enter no  56                                                                    
enter no  54                                                                    
enter no  87                                                                    
enter no  21                                                                    
enter no  27                                                                    
                                                                                
current data   27                                                               
current data   21                                                               
current data   87                                                               
current data   54                                                               
current data   56                                                               
 req data  87                                                                   
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
HAPPY-HAPPY                                                                     
HAPPY HAPPY                                                                     
HAPP   APPY                                                                     
HAP     PPY                                                                     
HA       PY                                                                     
HA       PY                                                                     
HAP     PPY                                                                     
HAPP   APPY                                                                     
HAPPY HAPPY                                                                     
HAPPY-HAPPY                                                                     
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
HAPPY-HAPPY                                                                     
HAPPY HAPPY                                                                     
HAPP   APPY                                                                     
HAP     PPY                                                                     
HA       PY                                                                     
HA       PY                                                                     
HAP     PPY                                                                     
HAPP   APPY                                                                     
HAPPY HAPPY                                                                     
HAPPY-HAPPY                                                                     
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
