#include<iostream.h>
#include<graphics.h>
#include<process.h>
#include<iomanip.h>
#include<string.h>
#include<conio.h>
#include<stdio.h>
#include<ctype.h>
#include<math.h>
#include<dos.h>


void main()
{	clrscr();
	cout<<"\nINT="<<sizeof(int);
	cout<<"\nUNSIGNED LONG INT="<<sizeof(unsigned long int);
	cout<<"\nSIGNED LONG INT="<<sizeof(signed long int);
	cout<<"\nFLOAT="<<sizeof(float);
	cout<<"\nDOUBLE="<<sizeof(double);
	cout<<"\nCHAR="<<sizeof(char);
	cout<<"\nUNSIGNED CHAR="<<sizeof(unsigned char);
	cout<<"\nSIGNED CHAR="<<sizeof(signed char);
	cout<<"\nLONG="<<sizeof(long);
	cout<<"\nUNSIGNED LONG="<<sizeof(unsigned long);
	cout<<"\nSIGNED LONG="<<sizeof(signed long);
    //cout<<"\n\aP\aR\aE\aS\aS\a \aA\aN\aY\a \aK\aE\aY\a \aT\aO\a \aC\aO\aN\aT\aI\aN\aU\aE\a \a.\a.\a.\a.\a.\a.\a.\a.\a.\a.\a.\a.\a";
	getche();
}































































































































